- name: django server
  become: true #to run as sudo
  hosts: public
  tasks:

    - name: "django project: copy project to ec2"
      synchronize:
        src: ./Booster_CI_CD_Project-master
        dest: /home/ubuntu
    
    - name: "django project: install python3"
      apt:
        name: python3
        update_cache: yes
    
    - name: "django project: install python3-pip"
      apt:
        name: python3-pip
    
    - name: "django project: install required packages"
      pip:
        requirements: /home/ubuntu/Booster_CI_CD_Project-master/requirements.txt

    - name: "django project: make migrations for DB"
      shell: python3 /home/ubuntu/Booster_CI_CD_Project-master/manage.py makemigrations
    
    - name: "django project: apply the migrations"
      shell: python3 /home/ubuntu/Booster_CI_CD_Project-master/manage.py migrate

    - name: "django project: start the server"
      shell: python3 /home/ubuntu/Booster_CI_CD_Project-master/manage.py runserver 0.0.0.0:8000 &
    
    - name: "apache: install"
      apt:
        name: apache2
      
    - name: "apache: change port to 8090 part1"
      lineinfile:
        path: /etc/apache2/ports.conf
        regexp: '^Listen 80'
        line: 'Listen 8090'
        backrefs: true
    
    - name: "apache: change port to 8090 part2"
      lineinfile:
        path: /etc/apache2/sites-enabled/000-default.conf
        regexp: '^<VirtualHost \*:80'
        line: '<VirtualHost *:8090>'
        backrefs: true
    
    - name: "apache: change web file"
      shell: echo "<h1>Hello from ansible</h1>" > /var/www/html/index.html  

    - name: "apache: restart service"
      shell: "systemctl restart apache2"